train_data_path: "data/processed/train_dataset.h5"
test_data_path: "data/processed/test_dataset.h5"

dataset:
  max_length: 50
  max_distance: 40
  sliding_window_step: 50
  train_mode: "random_crop"    # "truncate_seq" or "random_crop"
  val_mode: "sliding_window"   # "truncate_seq" or "sliding_window"
  use_msa: true
  num_msa_rows: 4
  num_angle_bins: 24
  train_batch_size: 8
  val_batch_size: 4

model:
  esm2_name: "esm2_t6_8M_UR50D"
  esm_msa_name: "esm_msa1b_t12_100M_UR50S"
  main_task: "contact"   # "contact" or "distance"
  use_contact: true
  use_distance: true
  use_angle: true
  num_layers_to_freeze_esm2: 6
  num_layers_to_freeze_msa: 12
  fusion_dim: 256
  fusion_num_layers: 4
  fusion_num_heads: 8

train:
  seed: 42
  num_epochs: 15
  contact_loss_type: "bce"    # "bce" or "focal"
  bce_contact_class_weights: [1.0, 30.0]
  learning_rate: 0.0001
  cosine_annealing_warm_restart_t_0: 10
  cosine_annealing_warm_restart_t_mult: 1
  cosine_annealing_warm_restart_eta_min: 0.000001
  focal_gamma: 2.0
  focal_alpha: 2.0
  contact_loss_weight: 1.
  distance_loss_weight: 0.25
  angle_loss_weight: 0.1
  use_scheduler: true
  overfit_one_batch: false

checkpoints:
  checkpoint_path_to_load: null
  checkpoints_dir_path: "checkpoints/"
  checkpoints_metric: "roc_auc"
  maximize_metric: true
  save_best_k_checkpoints: 2

mlflow:
  enabled: true
  tracking_uri: "http://localhost:5000"
  experiment_name: "just_exp"
  run_name: "v1"
